services:
  forma-backend:
    build: ./service-utilisateurs
    container_name: forma_backend
    env_file:
      - ./service-utilisateurs/.env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: ${JWT_SECRET:-Zm9ybWEtc3VwZXItc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtMjAyNQ==}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
    volumes:
      - uploads_data:/app/uploads

volumes:
  uploads_data:
